"""empty message

Revision ID: af49a896bafe
Revises: 235e49cc847e
Create Date: 2021-04-18 01:27:17.349268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af49a896bafe'
down_revision = '235e49cc847e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('diameter', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'diameter')
    # ### end Alembic commands ###
